version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
  db:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
