version: '3'
services:
  web:
    build: src
    ports:
      - "8080:8080"

  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/foo

volumes:
  db-data:
