name: Continuous Integration

on:
  pull_request:
    branches: [develop]
    paths:
      - 'server/**'
  push:
    branches: [develop]
    paths:
      - 'server/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: server

      - name: Run tests
        run: npm test
        working-directory: server
