name: Continuous Integration

on:
  pull_request:
    branches: [develop]
    paths:
      - 'server/**'
  push:
    branches: [develop]
    paths:
      - 'server/**'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          npm install
          npm test
